import type { Metadata } from "next"
import localFont from "next/font/local"

import { cn } from "@repo/ui/utils"

import "@repo/ui/styles"

import { Toaster } from "@repo/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("h-dvh", geistSans.variable, geistMono.variable)}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
