import type { Metadata } from "next"
import localFont from "next/font/local"
import MenuBar from "@/components/menu-bar"
import { ThemeProvider } from "@/components/theme-provider"

import { cn } from "@repo/ui/utils"

import "@repo/ui/styles"

import { Toaster } from "@repo/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-svh p-8", geistSans.variable, geistMono.variable)}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto h-full w-full max-w-[800px]">
            <MenuBar />
            <div className="mt-6">{children}</div>
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
